// Generated by mkskill from _mkskill/mkskill.config.xml - do not edit.
#define OT4XB_LOG_VER_MAJOR   1
#define OT4XB_LOG_VER_MINOR   0
#define OT4XB_LOG_VER_BUILD   0
#define OT4XB_LOG_VER_STRING  "v1.0.0"
